services:
  backend:
    build: ./atividadedevops-backend-main
    container_name: favstore-backend
    ports:
      - "8000:8000"
    volumes:
      - favstore-data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/database.db
      - CORS_ORIGINS=http://localhost:80,http://localhost:5173
    restart: unless-stopped

  frontend:
    build:
      context: ./atividadedevops-frontend-main
      args:
        - VITE_API_URL=http://localhost:8000
    container_name: favstore-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  favstore-data:
